[project]
org-name = "wso2"
version = "0.6.23"
license = ["Apache-2.0"]
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/module-consul"
keywords = ["Consul", "endpoint"]

[dependencies]
